# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - llm-it-dev-fe

on:
  push:
    branches:
      - dev-frontend
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'
    - name: Node modules installation and production build
      run: npm install --legacy-peer-deps && npm run build
      
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: 'liberica'
        java-version: '8.0.402'
        
    - name: Build project with Maven
      run: cd java && mvn clean install -DskipTests

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        context: .
        registry: https://llmitacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_649cf55218134197984ab66220c69054 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1c00c1075ed04bd89d908393358f50a2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: llmitacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_649cf55218134197984ab66220c69054 }}/llmit-fe-dev:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'llm-it-dev-fe'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3fcd0872593349f99c26e8d7082380c9 }}
        images: 'llmitacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_649cf55218134197984ab66220c69054 }}/llmit-fe-dev:${{ github.sha }}'
